
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CIUDAD CLAVE FECHA PREPconsulta : CLAVE PREP CIUDAD FECHAconsulta : CLAVE PREP CIUDAD PREP FECHA'
    
_lr_action_items = {'CLAVE':([0,],[2,]),'$end':([1,6,7,],[0,-1,-2,]),'PREP':([2,4,],[3,5,]),'CIUDAD':([3,],[4,]),'FECHA':([4,5,],[6,7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'consulta':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> consulta","S'",1,None,None,None),
  ('consulta -> CLAVE PREP CIUDAD FECHA','consulta',4,'p_consulta_simple','chatbot_parser.py',52),
  ('consulta -> CLAVE PREP CIUDAD PREP FECHA','consulta',5,'p_consulta_con_doble_prep','chatbot_parser.py',58),
]
